version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt pylint
  pre_build:
    commands:
      - python --version
      - pylint $CODEBUILD_SRC_DIR/*.py --errors-only
      #- pylint $CODEBUILD_SRC_DIR/job-portal/*.py --errors-only
artifacts:
  files:
    - '**/*'